version: 2
jobs:

  test_buy:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Sync Submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Create Simulator
          command: ./Scripts/setup_simulator
      - run:
          name: Test Buy iOS
          command: ./Scripts/test_buy
      - run:
          name: Test Buy tvOS
          command: ./Scripts/test_buy_tv
      - run:
          name: Test Buy watchOS
          command: ./Scripts/test_buy_watch
      
  test_pay:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Sync Submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Create Simulator
          command: ./Scripts/setup_simulator
      - run:
          name: Test Pay
          command: ./Scripts/test_pay
      
  test_sample:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Sync Submodules
          command: git submodule sync --recursive && git submodule update --recursive --init
      - run:
          name: Create Simulator
          command: ./Scripts/setup_simulator
      - run:
          name: Test Sample App
          command: ./Scripts/test_sample
      
workflows:
  version: 2
  test_suite:
    jobs:
      - test_buy
      - test_pay
      - test_sample
    